---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pv-claim
  namespace: example
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  volumeName: ebs-gp2-1